INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (1, true, '2021-10-21 11:17:18', 'Tắt Đèn là một trong những tác phẩm kinh điển của Ngô Tất Tố mà chắc chắn ai cũng đã từng đọc qua. Cuốn sách phác họa một bức tranh bi kịch, khổ đau và ác độc của xã hội cũ thời phong kiến. Ở nơi ấy, con người không được sống một cách bình thường, mà lúc nào cũng phải cúi đầu cam chịu những cay nghiệt mà các ông quan, trưởng làng đề ra...
 
Trung tâm câu chuyện kể về gia đình chị Dậu - một gia đình thuộc hạng nghèo nhất của xã hội. Trớ trêu thay, cái nghèo đấy lại không bắt nguồn từ gia đình chị Dậu mà bắt nguồn từ những chính sách vô lý của nhà nước.
 
Cho đến cuối cùng, số phận của nhân vật vẫn không có lối thoát, mọi thứ vẫn còn bị dang dở như thể đang chờ một câu trả lời cho số phận con người trong tương lai. Tác phẩm “Tắt Đèn” vẫn rất xứng đáng là tác phẩm kinh điển của nền văn học Việt Nam và là sự lựa chọn tốt cho những ai muốn tìm hiểu về một thời kỳ đen tối của đất nước.', '2021-10-26 16:09:25', 'Tắt Đèn', 100000.00, 15000.00, 1, 1, 0, 'https://cdn0.fahasa.com/media/catalog/product/i/m/image_119104.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (2, true, '2021-10-22 14:48:42', 'Những ai từng bị thu hút bởi những tác phẩm trung đại trong Sách giáo khoa thì hãy tìm ngay đến cuốn sách “Lều Chõng”. Nội dung cuốn sách thể hiện những mặt “rất phong kiến” khác nhau. Thể hiện rõ ràng và nổi bật nhất đó chính là sự phức tạp, rối rắm của việc thi cử đương thời, cái thời mà Tây - Ta - Tàu rất hỗn loạn và lộn xộn.
 
Đọc xong tác phẩm chắc hẳn bạn sẽ phải cảm thấy may mắn khi không phải sinh ra trong hình hài trai tráng giữa cái thời đại mà công danh đã trở thành chân lý không thể xóa bỏ. Bên cạnh đó ta sẽ thấy được lòng trọng dụng nhân tài, coi trọng tri thức của nhân dân Việt Nam. ', '2021-10-26 16:00:40', 'Lều Chõng', 120000.00, 10000.00, 1, 1, 0, 'https://firebasestorage.googleapis.com/v0/b/doan-shopping.appspot.com/o/leu-chong_1635235708034?alt=media&token=0e4930a5-4ce6-422c-b084-8dd7f92d5406');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (3, true, '2021-10-22 14:48:44', 'Không phải ngẫu nhiên mà người ta xưng tụng Ngô Tất Tố là nhà văn hóa chứ không chỉ là nhà văn. Ngô Tất Tố có sự nghiệp văn học cực kì vĩ đại và đồ sộ. Văn chương của ông là thước đo để định hình cho những cây bút khác trong làng văn học Việt Nam.
 
“Tuyển Tập Ngô Tất Tố” là cuốn sách tập hợp các bài văn hay và đặc sắc nhất của nhà văn Ngô Tất Tố. Với giọng văn trào phúng đạt đến đỉnh cao, người đọc sẽ vừa đọc vừa cảm nhận được nụ cười chua chát. Đây có lẽ là  một cuốn sách đáng mua và đáng đọc của Ngô Tất Tố.', '2021-10-22 15:05:42', 'Tuyển Tập Ngô Tất Tố', 150000.00, 30000.00, 1, 1, 3, 'https://cf.shopee.vn/file/e667b032c2d676e25f00d92c4cb92094');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (4, true, '2021-10-22 14:48:44', 'Nếu như “Số đỏ” là một tiểu thuyết khiến người đọc cười dài, thì “Giông tố” lại khiến người đọc thấy bi quan vô cùng về hiện thực đời sống. Trong bức tranh “Giông tố”, hiện lên những tên quan vô lại, vô nhân tính, cả đời chỉ có hưởng thụ tiền bạc và dâm dục. 
Cô gái Mịch, nhân vật chính của tác phẩm, chịu biết bao nhiêu là đàm tiếu, bị chính những hủ tục trong xã hội cũ dày và bị cái nghèo khổ dày vò đến mức phải cưới chính kẻ đã cưỡng hiếp mình, để lại trong lòng độc giả nhi
ều day dứt. Không chỉ tố cáo sự thối nát trong chế độ làng xã thôn quê, sự bóc lột người cùng đinh của bọn giàu có, quan lại, Vũ Trọng Phụng còn gợi lên hình ảnh con người của mọi thời dưới khía cạnh thực nhất: sự thay lòng đổi dạ trong một môi trường xã hội mà tiền bạc có thể chi phối tất cả', '2021-10-22 14:30:22', 'Giông tố', 80000.00, 0.00, 1, 1, 0, 'https://gacsach.com/sites/gacsach.com/files/giong-to_1.gif');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (5, true, '2021-10-21 11:18:01', 'Tuy không tạo được tiếng vang như “Số đỏ” và “Giông tố”, “Vỡ đê” vẫn tiếp tục làm sắc nét thêm chủ nghĩa hiện thực phê phán mà Vũ Trọng Phụng theo đuổi. Tác phẩm thông qua việc trình bày vấn đề tranh đấu của người dân đi hộ đê, phản ánh hiện thực trên một phạm vi khá rộng, từ thành thị đến nông thôn, song tập trung lên án những chính sách, thủ đoạn thống trị của bọn thực dân, quan lại đã đẩy người nông dân vào tình cảnh đói rét cơ cực. Đọc từng trang văn của ông, người ta không khỏi ngậm ngùi, chua chát vì một xã hội bê bối với những tấn trò đời bi kịch đương thời, một vũ trụ đen tối mà con người đối xử với nhau không hơn gì loài thú bởi khía cạnh bất nhân trong nhân tính.', null, 'Vỡ đê', 99000.00, 15000.00, 2, 1, 0, 'https://cf.shopee.vn/file/57acfd6fb1f925965bb49467374524d0');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (6, true, '2021-10-21 11:18:02', 'Là cuốn sách được xếp vào hàng táo bạo nhất trong sự nghiệp của tác giả Vũ Trọng Phụng, “Làm đĩ” chịu bao nhiêu lời phê bình cay độc lúc đương thời nhưng lại có sức sống và cuốn hút người đọc cho đến tận hôm nay. Được viết dưới dạng tự truyện của nhân vật chính tên Huyền, sinh ra trong một gia đình có cha làm việc cho Tây nhưng lại cực kỳ hủ bại, từ nhỏ Huyền đã luôn bị người lớn lảng tránh và nạt nộ khi cô bé thắc mắc về những vấn đề giới tính. Lớn lên, Huyền bắt đầu đời sống trụy lạc, gắn liền với khát khao tính dục, sống trong ô nhục và tủi cực sau nhiều biến cố của cuộc đời. Không chỉ nói về Huyền, tác phẩm còn tố cáo xã hội thành thị Việt Nam thời ấy đang “ u hóa” một cách nửa mùa – cái cũ chưa qua, cái mới chưa tới, đầy rẫy sự nhốn nháo, lừa lọc, sa đọa và đau khổ.', null, 'Làm đĩ', 170000.00, 20000.00, 2, 1, 0, 'https://cf.shopee.vn/file/5595a01670964d0295b156e5f4b5f2c5');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (7, true, '2021-10-21 11:18:03', '“Số đỏ” gần như là tác phẩm quen thuộc nhất của tác giả Vũ Trọng Phụng bởi lẽ đã xuất hiện trong chương trình giáo dục phổ thông, được xem là tiểu thuyết trào phúng tiêu biểu giai đoạn 1930-1945. Gã ma cà bông vô học Xuân Tóc Đỏ, từ một kẻ hạ lưu – nhờ vào những gian trá lừa lọc rất đúng thời điểm, hợp thời trang với trào lưu u hóa lúc bấy giờ – thành một người có địa vị danh giá vào hạng bậc nhất trong xã hội, đã trở thành hình tượng bất hủ của văn học Việt Nam. Qua tác phẩm này, nhiều người đã đánh giá Vũ Trọng Phụng đã phanh phui “thú tính” nơi con người, trong khi những tác giả hiện thực cùng thời mới chỉ phân chia xã hội thành hai lớp lang tốt và xấu, đề cao cái tốt và hạ bệ cái xấu.', null, 'Số đỏ', 140000.00, 50000.00, 2, 1, 0, 'https://salt.tikicdn.com/ts/product/a7/14/57/2160a52816265cd80ea8cdc7519418f2.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (8, true, '2021-10-21 11:18:03', 'Côn Đảo từ lâu đã là một "địa ngục trần gian". Không ai dám nói ngược lại, báng bổ vong linh những người đã đổ máu ở đảo này mà phải tội! Ta kính cẩn tin vào chuyện đó, không cần lý lẽ nhiều lời, và sau này lại còn có cả những tư liệu thực chứng cho thấy niềm tin của ta không sai. Đến những năm 1950, cuộc sống ở hòn đảo đó càng khủng khiếp. Hơn hai trăm tù binh bị giặc bắt từ khắp các chiến trường đã bị đưa về giam trên hòn đảo "địa ngục trần gian" này. Cái gì đã đoàn kết họ lại, cái gì đã phả sức chiến đấu vào những bắp thịt bị hành hạ đến héo mòn, cái gì khiến họ yêu thương nhau hơn cả anh em ruột thịt? Những chuyện kể của những người sống sót khỏi chốn địa ngục đó mà Phùng Quán gặp và ghi được tại nơi trao đổi tù binh sau Hiệp nghị Geneva 1954, toàn bộ cái mãnh liệt tinh thần của họ và ngay cả toàn bộ cái mong manh thân xác họ mang được từ địa ngục trở về đã làm nên một Phùng Quán của Côn Đảo, đã nhào nặn một Phùng Quán nữa cho Côn Đảo, và sự cộng hưởng tài tình và ân tình nơi Phùng Quán đã tổ chức lại được một cuộc vượt Côn Đảo khác, có thể ít thật hơn hoặc còn rất xa mới gần được sự thật, nhưng lại thiêng liêng vô cùng và được lưu giữ đến mãi mãi, một chuyến vượt ngục bất thành nhưng là cả một hình hài nằm trong cuốn sách mỏng chưa đến 200 trang!', null, 'Vượt Côn Đảo (Tái Bản 2016)', 200000.00, 40000.00, 3, 1, 0, 'https://www.khaitam.com/Data/Sites/1/Product/10540/vuot-con-dao.png');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (9, true, '2021-10-21 11:29:57', 'Có lẽ đây là tập thơ hay nhất và kỳ lạ nhất của Phùng Quán. Ở tập thơ này, anh kết hợp văn xuôi với thơ. Văn xuôi vừa như lời dẫn dụ vào thơ, nhưng đồng thời lại cũng chính là thơ với nhiều chi tiết, tâm trạng và quan niệm được chắt lọc', null, 'Trăng Hoàng Cung', 140000.00, 10000.00, 3, 1, 0, 'https://salt.tikicdn.com/cache/400x400/ts/product/f9/70/05/6301a9316da825b529ca27b2e0a5e822.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (10, true, '2021-10-21 11:29:59', 'Tuổi thơ dữ dội - cuốn truyện xoay quanh cuộc sống chiến đấu và hy sinh của những thiếu niên 13, 14 tuổi trong hàng ngũ Đội thiếu niên trinh sát của trung đoàn Trần Cao Vân. Những Lượm, Mừng, Quỳnh sơn ca, Hòa đen, Bồng da rắn, Vịnh sưa, Tư dát... mỗi người một hoàn cảnh song đều chung quyết tâm, nhiệt huyết và lòng yêu nước, đã tham gia chiến đấu hết mình và hy sinh khi tuổi đời còn rất trẻ.

Đúng như tên truyện, độc giả sẽ bắt gặp ở đó những chi tiết thực sự dữ dội về cuộc đời thiếu niên bất hạnh, về cuộc chiến tranh chống giặc tàn khốc nhưng ẩn sâu bên trong ta vẫn thấy những tâm hồn trong sáng và vô tư, thấy sự can trường, dũng cảm phi thường của nhân vật. Tất cả những ai đã từng đọc tác phẩm này hầu như đều không ngăn được xúc động và những giọt nước mắt cảm thương, cảm phục. Đây thực sự là một tác phẩm quý trong kho tàng văn học Việt Nam. Một câu chuyện khơi dậy trong mỗi người tình yêu đất nước và niềm trân trọng ký ức tuổi thơ...', null, 'Tuổi Thơ Dữ Dội', 120000.00, 150000.00, 3, 1, 0, 'https://salt.tikicdn.com/cache/w1200/media/catalog/product/t/u/tuoi-tho-du-doi-a.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (11, true, '2021-10-21 11:30:00', 'Trong tác phẩm Những Người Khốn Khổ, cuộc sống cao đẹp của Giăngvăngiăng – người phải ngồi tù suốt 19 năm chỉ vì một chiếc bánh mỳ, tình nhân ái bao dung và tấm lòng độ lượng của đức cha Mirien, sự đeo bám dai dẳng của mật thám Giave, những mưu đồ đen tối và độc ác của vợ chồng Tênácđiê, sự ngây thơ trong trắng của Côdét, sự nhiệt tình hăng hái của Mariuýt… Tất cả đều được khắc họa một cách sinh động.

Những Người Khốn Khổ là bài hát ca ngợi tình yêu và tự do của Giăngvăngiăng – một con người tái sinh trong đau khổ và tuyệt vọng.', null, 'Những Người Khốn Khổ', 130000.00, 15000.00, 5, 4, 0, 'https://gacsach.com/sites/gacsach.com/files/sach-nhung-nguoi-khon-kho.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (12, true, '2021-10-21 11:30:00', 'Nhà thờ Đức Bà Paris là tác phẩm tiêu biểu cho phong cách sáng tác theo khuynh hướng lãng mạn của Victor Hugo. Cũng nhờ thành công của tác phẩm mà ông được biết đến như một nhà văn nhân đạo, lãng mạn bậc nhất của nước Pháp. Bằng cốt truyện khá bi thảm, nặng nề, các tình tiết xếp đặt khéo léo, mang kịch tính và hình ảnh tô đậm, phóng đại, lẫn lộn thực hư, kết hợp với bút pháp miêu tả thật rực rỡ, kỳ thú, Victor Hugo đã vẽ nên một bức tranh thu nhỏ về xã hội Pháp thế kỷ XV.

“Cạnh ngôi nhà thờ lớn cổ kính, Victor Hugo xây dựng một tòa nhà thờ lớn khác bằng thi ca, cũng vững chắc như nền móng, cũng ngất cao như dãy tháp của tòa nhà thờ nọ”.', null, 'Nhà Thờ Đức Bà Paris', 180000.00, 22000.00, 5, 4, 0, 'https://static.epub.vn/epubvn-image/optimized-cover-1555429608555-ezgif-1-29f07dc7de4e.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (13, true, '2021-10-21 11:30:01', 'Tác phẩm ghi lại 24 giờ cuối cùng của cuộc đời một tử tù qua nhật ký của nhân vật xưng tôi – nhân vật không tên tuổi, lai lịch, không nguồn gốc tội lỗi, không ai biết anh ta phạm tội gì đến nỗi trở thành tử tù. Anh ta kể về không gian sinh tồn là nhà tù, những con người va chạm với anh ta trong 24 giờ đó là bạn tù, linh mục, cai ngục… và những người phụ nữ trong tâm tưởng gồm mẹ, vợ và con gái. Tất cả những suy tư đó đan xen với dòng suy nghĩ về việc anh ta sắp bị thi hành án.

Tác phẩm này gần như chứa đừng đầy đủ phong cách, mô típ nhân vật và chủ đề quen thuộc trong sáng tác văn xuôi của Victor Hugo. Đặc biệt hơn nữa, có lẽ đây là tác phẩm chứa đựng nhiều tâm sự thầm kín, những nhức nhối khôn cùng của một nhà văn suốt đời đấu tranh cho quyền “được sống” của con người: án tử hình và sự xóa bỏ vĩnh viễn nó khỏi cuộc sống nhân loại.', '2021-10-25 14:15:13', 'Ngày Cuối Cùng Của Một Tử Tù', 210000.00, 10000.00, 5, 4, 1, 'https://cdn0.fahasa.com/media/catalog/product/i/m/image_180164_1_43_1_57_1_4_1_2_1_210_1_29_1_98_1_25_1_21_1_5_1_3_1_18_1_18_1_45_1_26_1_32_1_14_1_2349.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (14, true, '2021-10-21 11:30:01', 'Lao động biển cả (Les Travailleurs de la mer) đã cuốn hút rất nhiều bạn đọc Việt Nam biết tiếng Pháp qua nhiều thế hệ. Đây không chỉ là một tác phẩm hiện thực phản ánh xã hội tư sản Pháp trong những ngày đầu của chế độ tư bản ở nước này. Qua tác phẩm này tác giả cũng xây dựng thành công một số nhân vật điển hình đại diện cho cái Thiện và cái Ác. Với một ngòi bút vững vàng đầy kinh nghiệm, tác giả đã vạch trần những mánh khóe xảo quyệt táng tận lương tâm của những con người như Rantaine hay Clubin. Đồng thời ông cũng miêu tả rất thực và rất sinh động những con người chân chính, lao động không mệt mỏi như Gilliatt. Qua câu chuyện tình éo le, dang dở của Gilliatt, bạn đọc vừa cảm thương cho số phận hẩm hiu của anh vừa căm giận những bất công trên đời này. Phải chăng đấy là một thứ “định mệnh của vạn vật”?', '2021-10-25 14:15:13', 'Lao Động Và Biển Cả', 300000.00, 50000.00, 5, 4, 1, 'https://salt.tikicdn.com/cache/w1200/media/catalog/product/l/a/lao-dong-va-bien-ca.gif');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (15, true, '2021-10-21 11:30:02', 'Tác phẩm lấy bối cảnh năm 1793 kinh hoàng của cuộc Cách mạng Pháp, mà người ta còn gọi là thời kỳ khủng bố, thời kỳ mà các cuộc tàn sát diễn ra đẫm máu ở cả hai phe, phe cộng hòa và phe bảo hoàng. Lúc này, De Lantenac trở về Pháp, cầm đầu dân quê Bretagne nổi dậy chống lại cách mạng. Gauvain, một vị tướng trẻ có tài, mà cũng là cháu ruột của De Lantenac, được cử đi dẹp loạn Vendée, dưới sự giám sát của Cimourdain. Anh đã thành công, sau ba tháng giao tranh, quân cộng hòa đã dồn De Lantenac vào đường cùng, nhưng hắn vẫn trốn thoát ngay đường tơ kẽ tóc. Lúc đó, một sự kiến bất ngờ đã diễn ra…', null, 'Chín Mươi Ba', 150000.00, 40000.00, 5, 4, 0, 'https://salt.tikicdn.com/cache/w1200/media/catalog/product/c/h/chin-muoi-ba.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (16, true, '2021-10-21 11:30:06', 'Bộ tiểu thuyết Thằng cười của Victor Hugo đưa chúng ta đến với nước Anh của thế kỷ XVII, chủ yếu dưới các triều đại của dòng họ Xtiua. Giắc II và Annơ Xtiua. Victor Hugo đã đưa vào Thằng cười không biết bao nhiêu chi tiếtlịch sử có thật của nước Anh thời bấy giờ với tên tuổi các ông vua, các nữ hoàng, nữ công tước, các vị nguyên lão, miêu tả tỉ mỉ chốn cung điện, các nghi thức triều đình… với một bút pháp độc đáo tài tình.', '2021-10-26 15:40:28', 'Thằng Cười', 100000.00, 5000.00, 5, 4, 0, 'https://trinhdinhlinh.com/sach/wp-content/uploads/2018/03/10891620_1397287557234036_3220596434129563960_n.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (17, true, '2021-10-21 11:30:07', 'Đứng đầu Top 10 tác phẩm văn học hay nhất của William Shakespeare là Romeo và Juliet (tên tiếng Anh: Romeo and Juliet). Đây là tác phẩm nổi tiếng nhất của William Shakespeare, được liệt vào hàng kinh điển mọi thời đại.



Romeo và Juliet là vở bi kịch về một mối tình lãng mạn mà oan trái, dựa trên sự việc có thật thời Trung Cổ. Tại thành Verona, hai dòng họ nhà Montague và Capulet có mối hận thù lâu đời. Thế nhưng trong một buổi dạ hội, Romeo và Juliet đã phải lòng nhau và yêu nhau sâu đậm. Mối hận thù giữa hai nhà càng tăng cao khi anh họ của Juliet giết chết người bạn thân của Romeo, Romeo trả thù và bị đày ải khỏi Verona. Trong khi đó, Juliet bị ép gả cho bá tước Paris. Để trốn đám cưới, Juliet uống một loại thuốc giả chết và nhờ một tu sĩ báo cho Romeo trở về cứu mình từ hầm mộ. Thế nhưng trước khi tu sĩ kịp báo cho Romeo, chàng đã nghe được tin về cái chết của Juliet và trở về giết Paris rồi tự sát. Khi Juliet tỉnh dậy, Romeo đã chết, quá đau đớn, nàng rút dao tự vẫn.



Giá trị nhân văn về tình yêu và bi kịch xã hội của Romeo và Juliet là trường tồn, được đánh giá là tác phẩm tiêu biểu nhất của William Shakespeare cả về câu từ lẫn cách tạo ra bi kịch. Tác phẩm có ảnh hưởng lớn, vừa lên án giới quý tộc ngày xưa, vừa là "sách giáo khoa" về cách tạo mâu thuẫn truyện cho các nhà văn, nhà viết kịch, nhà viết phim sau này.', null, 'Romeo và Juliet', 200000.00, 0.00, 6, 4, 0, 'https://cf.shopee.vn/file/ae759a95b1cff2d0acd7cbea15d255eb');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (18, true, '2021-10-21 11:30:07', 'Cùng với Romeo và Juliet, Hoàng tử Hamlet (tên tiếng Anh: Hamlet) cũng là một bi kịch nổi tiếng của đại văn hào William Shakespeare. Tác phẩm xoay quanh nhân vật Hamlet - hoàng tử Đan Mạch. Chàng gặp hoàn cảnh éo le khi vua cha vừa qua đời 2 tháng thì mẹ đã lấy Claudius - chú ruột của chàng. Một ngày nọ, hồn ma của vua cha về báo với Hamlet là chính Claudius đã giết vua, cướp ngôi. Hamlet vô cùng tức giận nhưng cũng lo sợ rằng hồn ma kia là do tà thuật tạo thành, vu oan cho Claudius để chàng giết Claudius, làm việc trái với luân thường đạo lý.



Để điều tra, Hamlet đã giả điên, trong khi đó Claudius muốn trừ khử Hamlet bèn đẩy chàng sang Anh và nhờ vua Anh giết Hamlet. Nhận ra được âm mưu ấy, Hamlet tráo đổi bức thư của Claudius viết cho vua Anh, rồi tìm cách quay trở về. Trong cuộc đấu kiếm cuối cùng, Claudius giao cho đối thủ của Hamlet một thanh kiếm tẩm độc, hắn còn bỏ độc vào rượu của Hamlet. Trong cuộc đấu kiếm, Hamlet bị đối thủ đâm trúng, nhưng đồng thời cũng lấy được kiếm của đối thủ và đâm trúng đối thủ và thành người chiến thắng. Bất ngờ xảy ra khi để ăn mừng Hamlet chiến thắng, chính hoàng hậu lại uống cốc rượu. Hoàng hậu trúng độc chết gây xôn xao dư luận. Tay kiếm đối thủ của Hamlet do bị đâm, biết mình không thoát chết nên đã nói rõ toàn bộ sự thật, bao gồm của việc Claudius là chủ mưu. Quá tức giận, Hamlet dùng thanh kiếm tẩm thuốc độc đâm Claudius rồi chết.', null, 'Hoàng tử Hamlet', 199000.00, 0.00, 6, 4, 0, 'https://downloadsach.com/wp-content/uploads/2016/01/hamlet-hoang-tu-dan-mach-ebook.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (19, true, '2021-10-21 11:30:08', 'Vua Macbeth (tên tiếng Anh: Macbeth) là vở bi kịch ngắn nhất của William Shakespeare, dựa trên giai thoại về vua Macbeth xứ Scotland. Theo đó, trước khi làm vua, Macbeth là một dũng tướng trung thành của Scotland. Sau một trận chiến, Macbeth gặp ba mụ phù thủy trong đám quân phản loạn và ba mụ đã đưa ra lời tiên tri rằng Macbeth sẽ trở thành vua xứ Scotland. Bị ám ảnh bởi lời tiên tri, lại được sự ủng hộ và kích động từ vợ, Macbeth đã tìm cách ám sát vua Scotland để trở thành vua Scotland.



Để thâu tóm quyền lực, Macbeth trở nên ác độc, không từ thủ đoạn, ra tay sát hại dòng dõi vua cũ cùng một loạt công thần, không từ phụ nữ và trẻ con. Dù vậy, một người con của cựu vương Scotland vẫn còn sống đã lãnh đạo quân nổi dậy, được sự trợ giúp của quân Anh tiến đánh Macbeth. Trong bối cảnh sắp bị đánh bại, vợ Macbeth đã tự sát. Macbeth phát điên và bị chết trong chiến trận sau đó. Đó là trận chiến mà anh ta phải đối mặt với Macduff, ban đầu không sợ hãi, vì anh ta nghĩ anh ta sẽ không thể bị giết bởi bất kỳ người đàn ông nào sinh ra từ phụ nữ. Macduff tuyên bố rằng anh ta đã "từ trong bụng mẹ của anh ta, Macbeth cuối cùng bị Macduff giết và chặt đầu. Trật tự được khôi phục và Malcolm lên ngôi Vua của Scotland.', null, 'Vua Macbeth', 160000.00, 18000.00, 6, 4, 0, 'https://product.hstatic.net/200000122283/product/nhung-tac-pham-de-doi-cua-shakespeare-macbeth-99mv3_8d3ece32145b44c9b00892c981b88979_grande.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (20, true, '2021-10-21 11:30:09', 'Vua Lear (tên tiếng Anh: King Lear) là vở kịch về vua Lear của nước Anh cổ xưa. Vào một ngày, khi đã già yếu, vua Lear gọi ba người con gái đến và bảo họ hãy ca ngợi mình. Trong khi hai người chị hết lời nịnh nọt vua cha thì người em gái út lại chỉ nói những lời thật lòng. Vua Lear nổi giận, đuổi con gái út đi và quyết định chia đôi đất nước cho hai cô con gái cả và con gái thứ hai, đồng thời gả hai cô cho hai công tước danh giá. Sau khi đã chia đôi đất nước, vua Lear sẽ sống nương nhờ hai người con gái, nào ngờ chỉ ít lâu sau, cả hai đã coi ông là một gánh nặng.



Họ tìm cách trốn tránh nghĩa vụ, cắt bỏ số lính hầu vua và đá quả bóng trách nhiệm cho người kia. Giữa hai người xảy ra tranh cãi và chiến tranh. Vua Lear trốn khỏi nhà và hóa điên. Trong lúc đó, cô con gái út đã cưới được hoàng tử nước Pháp, biết tin vua cha bị hai chị đuổi khỏi nhà và gây chiến tranh bèn dẫn quân Pháp về ứng cứu. Cordelia sẽ tìm ra cách mà các chị em đã làm với cha mình tàn nhẫn như thế nào. Cô tập hợp một đội quân và dẫn anh đến vương quốc của chị em. Trận chiến bắt đầu. Vua Lear và con gái út bị bắt. Đột nhiên, Edmund xuất hiện - đứa con trai khốn của Gloucester, người mà tác giả nhắc đến khi bắt đầu thảm kịch. Anh ta đang cố gắng tổ chức vụ giết Cordelia và cha cô. Nhưng anh ta chỉ thực hiện được một phần của kế hoạch, cụ thể là giết cô con gái nhỏ Lyra. Sau đó, Edmund chết trong một cuộc đấu tay đôi với anh trai Edgar. Tất cả các cô con gái của Vua Lear đều chết trong trận chung kết. Người lớn nhất giết chết người giữa và sau đó tự sát. Cordelia bị siết cổ trong tù. Vua Lear tự do và chết vì đau buồn.', null, 'Vua Lear', 250000.00, 30000.00, 6, 4, 0, 'https://downloadsach.com/wp-content/uploads/2017/01/Vua-lear-William-Shakespeare.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (21, true, '2021-10-21 11:30:09', 'Giông Tố (tên tiếng Anh: The Tempest) là tác phẩm kịch cuối cùng mà William Shakespeare tự viết. Bối cảnh chính của vở kịch được lấy trên một hòn đảo hoang chỉ có Prospero, vốn là công tước hợp pháp của Milan, sống cùng với con gái Miranda.



Họ bị lưu đày bởi Antonio, em trai của Prospero, người đã họp mưu với Alonso, vua xứ Naples, để hãm hại Prospero và chiếm ngôi. Xuyên suốt vở kịch là diễn biến những mưu mô của Prospero nhằm lấy lại quyền lực đã mất và tìm cách đưa Miranda lấy lòng Ferdinand, con trai của Alonso, để nàng trở thành hoàng hậu sau này.', null, 'Giông Tố', 220000.00, 40000.00, 6, 4, 0, 'https://images-na.ssl-images-amazon.com/images/I/81iUxqt5VdL.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (22, true, '2021-10-21 11:30:10', 'Othello (tên tiếng Anh: Othello) là vở kịch được William Shakespeare viết, dựa trên truyện ngắn của Ý có tên là "Un Capitano Moro" (Thuyền trưởng Maroc). Vở kịch được thiết lập chuyển động khi Othello, một vị tướng da đen anh hùng phục vụ Venice, bổ nhiệm Cassio và không Iago với tư cách là trung úy trưởng của mình. Ghen tị với thành công của Othello và ghen tị với Cassio, Iago bày mưu cho sự sụp đổ của Othello bằng cách ám chỉ sai vợ của Othello, Desdemona và Cassio trong một mối tình. Với sự trợ giúp vô tình của Emilia, vợ của anh ấy, và sự giúp đỡ sẵn lòng của Roderigo, một người bạn xấu tính, Iago thực hiện kế hoạch của mình.



Sử dụng một chiếc khăn tay của Desdemona và được Emilia tìm thấy khi Othello vô tình đánh rơi nó, Iago thuyết phục Othello rằng Desdemona đã đưa chiếc khăn tay cho Cassio như một biểu tượng tình yêu. Iago cũng dụ Othello nghe trộm cuộc trò chuyện giữa mình và Cassio thực chất là về tình nhân của Cassio, Bianca, nhưng điều mà Othello dẫn đến tin rằng liên quan đến sự say mê của Cassio với Desdemona. Những “bằng chứng” mảnh mai này xác nhận điều mà tất cả Othello đều quá khó tin - rằng, là một người đàn ông da đen lớn tuổi, ông không còn hấp dẫn người vợ trẻ người Venice da trắng của mình. Quá ghen tuông, Othello giết Desdemona. Khi biết được từ Emilia, quá muộn, rằng vợ mình là người vô tội, anh ta yêu cầu được ghi nhớ như một người "yêu không khôn ngoan nhưng quá tốt" và tự sát.', null, 'Othello', 140000.00, 12000.00, 6, 4, 0, 'https://cdn0.fahasa.com/media/catalog/product/cache/1/small_image/600x600/9df78eab33525d08d6e5fb8d27136e95/9/7/9782290338889.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (23, true, '2021-10-21 11:53:40', 'Vua Richard Đệ Nhị (tên tiếng Anh: King Richard II) là tác phẩm kịch lịch sử dựa trên lịch sử nước Anh về vua Richard II. Bi kịch xảy ra cho Richard II trong vụ xét xử công tước Henry Bolingbroke, lưu đày Bolingbroke khỏi nước Anh. Ít lâu sau, Bolingbroke đã quay về và thực hiện một cuộc đảo chính, buộc Vua Richard Đệ Nhị phải nhường ngôi cho mình.



Sau khi đã nhường ngôi cho Bolingbroke và Bolingbroke lên ngôi, lấy danh hiệu Henry V, Vua Richard Đệ Nhị đã bị ám sát dã man. Đây được coi như là sự kiện khởi đầu cho Chiến tranh Hoa hồng nổi tiếng trong lịch sử nước Anh mà sau này Game of Thrones lấy cảm hứng từ đó.', null, 'Vua Richard Đệ Nhị', 168000.00, 16000.00, 6, 4, 0, 'https://m.media-amazon.com/images/I/41JUtUFBpBL.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (24, true, '2021-10-21 11:53:42', 'Tiếp nối series kịch lịch sử về các vua nước Anh, Vua Henry Đệ Lục nói về đời cháu của Henry Đệ Tứ - người đã cướp ngôi của Richard II. Dưới thời của Vua Henry Đệ Lục, mâu thuẫn giữa nhà Lancaster của các vua Henry V, Henry VI và nhà York của hậu duệ Richard II.

Cuộc nội chiến nổi tiếng trong lịch sử nước Anh giữa hai nhà quý tộc lững lẫy đã kéo theo các phe phái, chỉ kết thúc khi sau này, Richard III bị đánh bại bởi Henry VII - con trai của Vua Henry Đệ Lục. Tác phẩm về Vua Henry Đệ Lục được Shakespeare viết làm ba phần, xuyên suốt cuộc đời của vị vua này lẫn cuộc Chiến tranh Hoa hồng.', null, 'Vua Henry Đệ Lục', 152000.00, 20000.00, 6, 4, 0, 'https://m.media-amazon.com/images/I/515Yap5iXaL.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (25, true, '2021-10-21 11:53:44', 'Julius Caesar Đại Đế (tên tiếng Anh: The Tragedy of Julius Caesar) là bi kịch Shakespeare viết về cuộc đời của Julius Caesar Đại Đế - một trong những nhân vật lịch sử La Mã nổi tiếng nhất mọi thời đại. Julius Caesar là 1 trong 2 quan chấp chính La Mã, cùng với Pompey.



Sau khi đánh bại Pompey, Julius Caesar lên ngôi hoàng đế, lấy danh hiệu nhà độc tài trọn đời. Điều này khiến cho nhiều thành viên của Viện nguyên lão không phục, để rồi một cuộc mưu sát tập thể đã diễn ra ngay trong Viện nguyên lão. Julius Caesar bị các nguyên lão mưu sát vào một ngày lên triều, với tổng cộng 23 nhát dao đâm.', null, 'Julius Caesar Đại Đế', 190000.00, 5000.00, 6, 4, 0, 'https://storage.googleapis.com/media365-live.appspot.com/b4f85bf3-c5ba-4c52-a2f6-452b1b157b8d/0ff6bb4e-a586-487a-a39a-09ffb388a0e7/f2401669-c7f2-4f6b-bea2-c03a06c47c3e.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (26, true, '2021-10-21 11:53:45', 'Và đứng cuối cùng trong Top 10 tác phẩm văn học hay nhất của William Shakespeare là Người lái đò thành Venice (tên tiếng Anh: The Merchant of Venice). Đây là tác phẩm kịch kể về cuộc kiện tụng và đấu tranh giữa Antonio - người lái đò tốt bụng, và Shylock - tên cho vay nặng lãi người Do Thái luôn tìm cách hãm hại Antonio.



Baxaniô một quý tộc trẻ, có học. Bạn thân là Antôniô, một thương gia giàu có ở Vơnidơ. Baxaniô cần tiền cưới vợ - công nương Porxia xinh đẹp. Antôniô không sẵn tiền vì tất cả tài sản của chàng đang lênh đênh trên 3 chiếc thuyền buôn chưa về. Antôniô phải đến vay của tên Shylock, một lái buôn Do Thái số tiền 3000 đuyca với điều kiện ghi vào văn khế: nếu sau 3 tháng không trả được nợ thì Shylock có quyền xẻo một cân thịt trên thân thể người vay nợ. Tuy yêu Baxaniô, nhưng công nương Porxia phải thực hiện đúng chúc thư của bố, người cầu hôn phải chọn đúng cái hòm trong đựng chân dung nàng mới được kết duyên cùng nàng. Ông hoàng Marốc chọn cái hòm vàng, mở ra chỉ thấy cái đầu lâu và một tờ thư châm biếm. Ông hoàng xứ Aragông chọn cái hòm bạc, trong chỉ có chân dung thằng ngốc với một bài thơ hài hước. Baxaniô chọn hòm chì, mở ra… và hạnh phúc đã thuộc về chàng.



Hạn nợ đã đến. Shylock kiện ra toà. Baxaniô và Graxianô (chồng nàng Nêrixa hầu gái của công nương Porxia phải cấp tốc về Vơnidơ. Được ông anh họ là quan toà viết thư ủy nhiệm, Porxia cải trang thành tiến sĩ luật khoa, nàng Nêrixa cải trang thành viên thư ký. Hai nàng đã được thống lĩnh mời vào ghế quan tòa. Porxia tuyên bố cho Shylock thực hiện đúng văn khế và lưu ý phải cắt đúng 1 cân thịt không hơn không kém trên thân thể Antôniô và không làm chảy ra một giọt máu nào. Sailốc bị thua kiện, bị ghép vào tội âm mưu hãm hại một công dân thành Vơnidơ, bị toà tuyên bố tịch thu toàn bộ tài sản.', null, 'Người lái đò thành Venice', 220000.00, 45000.00, 6, 4, 0, 'https://images-na.ssl-images-amazon.com/images/I/519KfsM6bRL._SX322_BO1,204,203,200_.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (27, true, '2021-10-21 11:55:03', 'Bộ Truyện tranh Thần đồng đất Việt có lẽ là bộ truyện tranh Việt Nam ghi dấu ấn nhất từ trước tới nay. Truyện vừa có nét vẽ mới, mang cốt truyện dân gian nhưng không hề gây nhàm chán bởi những tình huống hài hước.

Thần đồng đất Việt cũng là bộ truyện tranh gắn bó với tuổi thơ của thế hệ 8x, 9x thời bấy giờ, một điểm sáng hiếm hoi của truyện tranh Việt.


 
Nội dung truyện được bó gọn trong từng tập giúp người xem dễ dàng theo dõi. Hi vọng đây sẽ tiếp tục là một trong những bộ truyện được các bạn yêu thích.', null, 'Thần đồng đất Việt(Tập 1) ', 30000.00, 5000.00, 8, 3, 0, 'https://upload.wikimedia.org/wikipedia/vi/2/23/Than_dong_dat_viet.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (28, true, '2021-10-21 11:55:05', 'Bộ Truyện tranh Thần đồng đất Việt có lẽ là bộ truyện tranh Việt Nam ghi dấu ấn nhất từ trước tới nay. Truyện vừa có nét vẽ mới, mang cốt truyện dân gian nhưng không hề gây nhàm chán bởi những tình huống hài hước.

Thần đồng đất Việt cũng là bộ truyện tranh gắn bó với tuổi thơ của thế hệ 8x, 9x thời bấy giờ, một điểm sáng hiếm hoi của truyện tranh Việt.


 
Nội dung truyện được bó gọn trong từng tập giúp người xem dễ dàng theo dõi. Hi vọng đây sẽ tiếp tục là một trong những bộ truyện được các bạn yêu thích.', null, 'Thần đồng đất Việt(Tập 2) ', 30000.00, 5000.00, 8, 3, 0, 'https://salt.tikicdn.com/cache/w1200/media/catalog/product/t/h/than-dong-dat-viet-tap-2.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (29, true, '2021-10-21 11:55:06', 'Bộ Truyện tranh Thần đồng đất Việt có lẽ là bộ truyện tranh Việt Nam ghi dấu ấn nhất từ trước tới nay. Truyện vừa có nét vẽ mới, mang cốt truyện dân gian nhưng không hề gây nhàm chán bởi những tình huống hài hước.

Thần đồng đất Việt cũng là bộ truyện tranh gắn bó với tuổi thơ của thế hệ 8x, 9x thời bấy giờ, một điểm sáng hiếm hoi của truyện tranh Việt.


 
Nội dung truyện được bó gọn trong từng tập giúp người xem dễ dàng theo dõi. Hi vọng đây sẽ tiếp tục là một trong những bộ truyện được các bạn yêu thích.', null, 'Thần đồng đất Việt(Tập 3) ', 30000.00, 5000.00, 8, 3, 0, 'https://3.bp.blogspot.com/-z7GqY3K40NE/WWyOuN1-znI/AAAAAAAAAnI/85gefolQcKsGJsFmwg_erEyYCuylGn5XQCLcBGAs/s400/tddv-t3.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (30, true, '2021-10-22 14:54:45', 'Bộ Truyện tranh Thần đồng đất Việt có lẽ là bộ truyện tranh Việt Nam ghi dấu ấn nhất từ trước tới nay. Truyện vừa có nét vẽ mới, mang cốt truyện dân gian nhưng không hề gây nhàm chán bởi những tình huống hài hước.

Thần đồng đất Việt cũng là bộ truyện tranh gắn bó với tuổi thơ của thế hệ 8x, 9x thời bấy giờ, một điểm sáng hiếm hoi của truyện tranh Việt.


 
Nội dung truyện được bó gọn trong từng tập giúp người xem dễ dàng theo dõi. Hi vọng đây sẽ tiếp tục là một trong những bộ truyện được các bạn yêu thích.', '2021-10-22 14:55:35', 'Thần đồng đất Việt(Tập 4) ', 30000.00, 0.00, 8, 3, 1, 'https://salt.tikicdn.com/cache/400x400/media/catalog/product/t/d/tddv-t4.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (31, true, '2021-10-21 11:55:07', 'Bộ Truyện tranh Thần đồng đất Việt có lẽ là bộ truyện tranh Việt Nam ghi dấu ấn nhất từ trước tới nay. Truyện vừa có nét vẽ mới, mang cốt truyện dân gian nhưng không hề gây nhàm chán bởi những tình huống hài hước.

Thần đồng đất Việt cũng là bộ truyện tranh gắn bó với tuổi thơ của thế hệ 8x, 9x thời bấy giờ, một điểm sáng hiếm hoi của truyện tranh Việt.


 
Nội dung truyện được bó gọn trong từng tập giúp người xem dễ dàng theo dõi. Hi vọng đây sẽ tiếp tục là một trong những bộ truyện được các bạn yêu thích.', null, 'Thần đồng đất Việt(Tập 5) ', 30000.00, 10000.00, 8, 3, 0, 'https://salt.tikicdn.com/media/catalog/product/t/d/tddv-t5.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (32, true, '2021-10-21 11:55:07', 'Bộ Truyện tranh Thần đồng đất Việt có lẽ là bộ truyện tranh Việt Nam ghi dấu ấn nhất từ trước tới nay. Truyện vừa có nét vẽ mới, mang cốt truyện dân gian nhưng không hề gây nhàm chán bởi những tình huống hài hước.

Thần đồng đất Việt cũng là bộ truyện tranh gắn bó với tuổi thơ của thế hệ 8x, 9x thời bấy giờ, một điểm sáng hiếm hoi của truyện tranh Việt.


 
Nội dung truyện được bó gọn trong từng tập giúp người xem dễ dàng theo dõi. Hi vọng đây sẽ tiếp tục là một trong những bộ truyện được các bạn yêu thích.', null, 'Thần đồng đất Việt(Tập 6) ', 30000.00, 5000.00, 8, 3, 0, 'https://salt.tikicdn.com/cache/w1200/media/catalog/product/t/d/tddv-t6.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (33, true, '2021-10-21 11:55:08', '', null, 'Toán 1 - Tập một', 20000.00, 0.00, 4, 2, 0, 'https://cf.shopee.vn/file/b2c547089728fbb32752d284224be980');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (34, true, '2021-10-21 11:55:09', '', null, 'Toán 1 - Tập hai', 18000.00, 0.00, 4, 2, 0, 'https://cf.shopee.vn/file/27c48655b3192df119be55dbfee44ab9');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (35, true, '2021-10-21 11:55:09', null, null, 'Tiếng Việt 1 - Tập một', 22000.00, 0.00, 4, 2, 0, 'https://cf.shopee.vn/file/fabdeb42d2cf8df7901f04c37aafca23');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (36, true, '2021-10-21 11:55:10', null, null, 'Tiếng Việt 1 - Tập hai', 20000.00, 0.00, 4, 2, 0, 'https://cf.shopee.vn/file/a6a523db059d666f18f06885c23ee6f2');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (37, true, '2021-10-21 12:01:51', null, null, 'Tự nhiên và Xã hội 1', 20000.00, 0.00, 4, 2, 0, 'https://product.hstatic.net/200000047766/product/bia_1-4_tu_nhien_xa_hoi_1-shs-01_a2b71f9eb2e94b0c848c2efc0b537f70.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (38, true, '2021-10-21 12:01:53', null, null, 'Đạo đức 1', 20000.00, 0.00, 4, 2, 0, 'https://product.hstatic.net/200000047766/product/bia_1-4_dao_duc_1-shs-01_cb0cf09dab864ed1aab381175304d232_master.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (39, true, '2021-10-21 12:01:53', null, null, 'Âm nhạc 1', 20000.00, 0.00, 4, 2, 0, 'https://product.hstatic.net/200000047766/product/bia_1-4_am_nhac_1-shs-01_7339f4a53e464931b11094c1b37e91bb_master.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (40, true, '2021-10-21 12:01:54', null, null, 'Mĩ thuật 1', 20000.00, 0.00, 4, 2, 0, 'https://product.hstatic.net/200000047766/product/bia_1-4_my_thuat_1-shs-01_1b788977563048f880190285148f8e6f_master.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (41, true, '2021-10-21 12:01:54', null, null, 'Giáo dục thể chất 1', 20000.00, 0.00, 4, 2, 0, 'https://product.hstatic.net/200000047766/product/untitled_221085c1bff74681be6c4852f5585e75.png');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (42, true, '2021-10-21 12:01:55', null, null, 'Hoạt động trải nghiệm 1', 20000.00, 0.00, 4, 2, 0, 'https://product.hstatic.net/200000047766/product/bia_hoat_dong_trai_nghiem_1-shs-01_6f3c7917de9843e28e8c5211b5809201_master.jpg');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (43, true, '2021-10-21 13:13:54', null, null, 'Tiếng Anh 1', 20000.00, 0.00, 4, 2, 0, 'http://product.hstatic.net/200000047766/product/bia-tienganh1-shs-300_43e014ceb16440e587a637bba5b5181f_grande.png');
INSERT INTO `doan-shopping`.book (id, active, date_created, description, last_updated, name, price, sale_price, author_id, book_category_id, sold, image_url) VALUES (44, true, '2021-10-26 14:45:01', 'test1', '2021-10-26 15:41:54', 'test1', 0.00, 0.00, 1, 1, 0, 'https://firebasestorage.googleapis.com/v0/b/doan-shopping.appspot.com/o/imgbin_samsung-galaxy-a8-a8-user-login-telephone-avatar-png_1635234969050?alt=media&token=16a24feb-0032-4407-9894-f6f65aaee4d8');